#!/usr/bin/env python3
"""Generate AUDIT.md: artefacts, model health, data checks, endpoint status.

Everything is read from the result files and the live machine at generation time,
so the page cannot drift from what is actually there.
"""
import json, os, subprocess, glob, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BRAIN = os.path.expanduser("~/brain_run")
R = lambda n: json.load(open(os.path.join(ROOT, "results", n)))


def sh(cmd):
    try:
        return subprocess.run(cmd, shell=True, capture_output=True, text=True,
                              timeout=30).stdout.strip()
    except Exception:
        return ""


def main():
    res, te, deg = R("RESULTS.json"), R("tingting_endpoints.json"), R("policy_degeneracy.json")
    pt = R("primary_test.json")
    L = []
    A = L.append

    A("# Audit page\n")
    A("Generated by `analysis/build_audit.py` from the result files and the live machine.\n")

    # ---------- 1. models
    A("\n## 1. Model health\n")
    ol = sh("ollama list")
    if ol:
        A("```")
        A(ol)
        A("```")
        A("\nStore: `~/.ollama/models`, %s on disk. Models persist across restart."
          % (sh("du -sh ~/.ollama/models 2>/dev/null | cut -f1") or "unknown"))
    else:
        A("`ollama list` returned nothing at generation time.")
    A("\nInference settings used for every run in this project: temperature 0, seed %s, "
      "model `%s`. Determinism is what makes the paired tests valid."
      % (res.get("seed"), res.get("model")))
    ba = pt.get("baseline_agreement", {})
    if ba:
        A("\nDeterminism verified, not assumed: the baseline was recorded independently by two "
          "arms that ran at different times and agreed **%d/%d**."
          % (ba["agree"], ba["n"]))

    # ---------- 2. data checks
    A("\n## 2. Data integrity checks\n")
    A("An exposure is one model decision in one experimental cell. Two records sharing an identity "
      "key are a repeated write, not a repeated measurement, and the second is dropped.\n")
    A("| arm | exposures | duplicate writes dropped | gate quarantined | identity key |")
    A("|---|---|---|---|---|")
    tot_dup = 0
    for arm, m in res["_integrity"].items():
        tot_dup += m["duplicate_writes_dropped"]
        A("| %s | %d | %d | %d | %s |" % (arm, m["n"], m["duplicate_writes_dropped"],
                                          m["gate_quarantined"], " + ".join(m["key"])))
    A("\n**%d duplicate writes found and dropped in total.** Cause and fix in `DATA_INTEGRITY.md`."
      % tot_dup)

    A("\n### Data governance\n")
    A("| check | result |")
    A("|---|---|")
    n_data = len([f for f in sh("git ls-files").split("\n")
                  if f.endswith((".jsonl", ".parquet", ".csv.gz"))])
    n_ids = sh("git grep -lIE '[0-9]{8}_[0-9]{5,8}' -- '*.md' '*.py' '*.json' '*.txt' | wc -l").strip()
    A("| patient-data files tracked in git | %d |" % n_data)
    A("| tracked text files containing a case_id-shaped string | %s |" % (n_ids or "0"))
    A("| repository visibility | %s |" % (sh("gh repo view --json visibility -q .visibility") or "unknown"))
    A("| run data location | `~/brain_run/runs`, never committed |")
    A("\n`case_id` is `subject_id` + `_` + `micro_specimen_id`, so quoting one republishes two "
      "credentialed identifiers. That is why the count above must stay at zero.")

    # ---------- 3. endpoint status
    A("\n## 3. Endpoint status against the supervisor's hierarchy\n")
    pa = te["primary_appropriateness"]
    sp = te["spectrum_appropriateness"]
    sy = te["sycophancy_under_pressure"]
    hrrs = [v["HRR"]["pct"] for v in sy.values() if v["HRR"]["pct"] is not None]
    bcrs = [v["BCR"]["pct"] for v in sy.values() if v["BCR"]["pct"] is not None]
    A("| endpoint | status | value |")
    A("|---|---|---|")
    A("| 1. Appropriateness vs susceptibility (primary) | done | baseline %.1f%%, panel revealed %.1f%%, gain %+.1f pts |"
      % (pa["baseline_pre_culture"]["pct"], pa["with_panel_revealed"]["pct"],
         pa["gain_from_evidence_pts"]))
    A("| 2. Active therapy concordance | done | same measure, reported per condition |")
    A("| 3. Time to appropriate therapy | done | see `SCORECARD.txt` |")
    A("| 4. Spectrum appropriateness | done | carbapenem %.1f%% baseline to %.1f%% under pressure, %.1f%% with the panel |"
      % (sp["baseline"]["carbapenem_pct"], sp["under_pressure"]["carbapenem_pct"],
         sp["panel_revealed"]["carbapenem_pct"]))
    A("| 5. Escalation / de-escalation correctness | done | see `SCORECARD.txt` |")
    A("| 6. Treatment failure | done, secondary | see `SCORECARD.txt` |")
    A("| 7. Mortality | done, secondary, not causal | see `SCORECARD.txt` |")
    A("| 8. Length of stay / ICU | done, secondary | see `SCORECARD.txt` |")
    A("| Sycophancy: HRR and BCR | done | HRR %.1f to %.1f%%, BCR %.1f to %.1f%% |"
      % (min(hrrs), max(hrrs), min(bcrs), max(bcrs)))
    A("| Sycophancy: confidence before and after | done | recorded per case, correct-and-confident to wrong-and-confident counted |")
    A("| Pre-specified primary test (protocol s7) | done | c = 0 under every framing, p at worst %.3g |"
      % max(v["discordant"]["p_exact"] for v in pt["by_framing"].values()))

    # ---------- 4. artefacts
    A("\n## 4. Artefacts and what generates them\n")
    A("| artefact | generated by | source of numbers |")
    A("|---|---|---|")
    for doc, gen, src in [
        ("STORY.md", "analysis/render_story.py", "results/*.json"),
        ("PRIMARY_TEST.md", "analysis/render_primary.py", "results/primary_test.json"),
        ("HEADLINE_RESULT.md", "analysis/render_headline.py", "results/RESULTS.json"),
        ("OUTSTANDING.md", "analysis/build_outstanding.py", "swept supervisor asks"),
        ("AUDIT.md", "analysis/build_audit.py", "results/*.json and the live machine"),
        ("results/RESULTS.json", "analysis/canonical_numbers.py", "run data, deduplicated"),
        ("results/tingting_endpoints.json", "analysis/tingting_endpoints.py", "run data"),
        ("results/primary_test.json", "analysis/primary_test.py", "run data"),
        ("results/policy_degeneracy.json", "analysis/policy_degeneracy.py", "run data"),
        ("SCORECARD.txt", "analysis/supervisor_scorecard.py", "run data"),
    ]:
        A("| `%s` | `%s` | %s |" % (doc, gen, src))
    A("\nDocuments written by hand, not generated: `METHODS.md`, `LIMITATIONS.md`, "
      "`DATA_INTEGRITY.md`, `CHANGELOG.md`, `README.md`, `protocol/`.")

    A("\n### Repository\n")
    A("| | |")
    A("|---|---|")
    A("| tracked files | %s |" % sh("git ls-files | wc -l").strip())
    A("| commits | %s |" % sh("git rev-list --count HEAD").strip())
    A("| head | `%s` |" % sh("git log --oneline -1"))
    A("| remote in sync | %s |" % ("yes" if sh("git rev-parse HEAD") ==
                                   sh("git rev-parse @{u} 2>/dev/null") else "check"))

    # ---------- 5. run state
    A("\n## 5. Run state\n")
    A("| arm | exposures on disk |")
    A("|---|---|")
    for arm in ("D_MATCH_1", "D_CALIB_1"):
        A("| %s | %d |" % (arm, res["_integrity"][arm]["n"]))
    fs = glob.glob(os.path.join(BRAIN, "runs", "fewshot_*.jsonl"))
    A("| few-shot | %d |" % sum(1 for f in fs for _ in open(f)))
    A("\nResume everything with `cd ~/brain_run && ./go.sh`. Each arm runs under a PID lock so a "
      "second copy is refused rather than allowed to interleave.")

    open(os.path.join(ROOT, "AUDIT.md"), "w").write("\n".join(L) + "\n")
    print("wrote AUDIT.md")


if __name__ == "__main__":
    main()
